// Pure type exports - no runtime dependency on drizzle
// These types are erased at compile time

// DB Types ($ prefix)
export type {
  $User,
  $UserIns,
  $UserUpd,
  $Article,
  $ArticleIns,
  $ArticleUpd,
  $Category,
  $CategoryIns,
  $CategoryUpd,
  $Tag,
  $TagIns,
  $TagUpd,
  $Draft,
  $DraftIns,
  $DraftUpd,
  $DraftVersion,
  $DraftVersionIns,
  $StaticFile,
  $StaticFileIns,
  $SiteMeta,
  $SiteMetaIns,
  $SiteMetaUpd,
  $LoginLog,
  $LoginLogIns,
  $CustomPage,
  $CustomPageIns,
  $CustomPageUpd,
  $Analytics,
  $AnalyticsIns,
  $PermissionNode,
  $PermissionNodeIns,
  $PermissionNodeUpd,
  $PermissionGroup,
  $PermissionGroupIns,
  $PermissionGroupUpd,
  $PluginData,
  $PluginDataIns,
  $PluginDataUpd,
  $Webhook,
  $WebhookIns,
  $WebhookUpd,
  $WebhookLog,
  $WebhookLogIns,
} from '../runtime/schema.js';

// API Types (no prefix)
export type {
  User,
  UserReq,
  UserPatch,
  Article,
  ArticleReq,
  ArticlePatch,
  ArticleList,
  Category,
  CategoryReq,
  CategoryPatch,
  Tag,
  TagReq,
  TagPatch,
  Draft,
  DraftReq,
  DraftPatch,
  DraftList,
  DraftVersion,
  StaticFile,
  StaticFileReq,
  SiteMeta,
  SiteMetaReq,
  SiteMetaPatch,
  LoginLog,
  CustomPage,
  CustomPageReq,
  CustomPagePatch,
  Analytics,
  PermissionNode,
  PermissionNodeReq,
  PermissionNodePatch,
  PermissionGroup,
  PermissionGroupReq,
  PermissionGroupPatch,
  PluginData,
  PluginDataReq,
  PluginDataPatch,
  Webhook,
  WebhookReq,
  WebhookPatch,
  WebhookLog,
} from '../runtime/schema.js';
