#!/bin/sh
set -e

# Dev entrypoint: PocketBase (API) + Theme Host (SSR frontend) + Caddy (HTTPS + routing)
#
# Caddy boots with bootstrap.json, then pb's OnBootstrap hook calls LoadConfig
# via admin API to inject full routes. Entrypoint is PID 1, Caddy runs in background.

PB_HTTP="127.0.0.1:8090"
PB_DATA="${VANBLOG_DATA_DIR:-/pb_data}"

# --- VANBLOG_HTTP_ONLY: pick the TLS-less bootstrap config when set ---
BOOTSTRAP_JSON="/etc/caddy/bootstrap.json"
if [ "${VANBLOG_HTTP_ONLY}" = "1" ] || [ "${VANBLOG_HTTP_ONLY}" = "true" ]; then
  echo "[vanblog] HTTP_ONLY mode: external proxy terminates TLS"
  BOOTSTRAP_JSON="/etc/caddy/bootstrap-http-only.json"
fi

echo "[vanblog] starting in DEV mode"
echo "[vanblog] pb data: $PB_DATA"

# --- Health check helper ---
wait_for() {
  url="$1"
  name="$2"
  max="${3:-30}"
  i=0
  while [ $i -lt $max ]; do
    if wget -q -O /dev/null -T 1 "$url" 2>/dev/null; then
      echo "[vanblog] $name is ready (took ${i}s)"
      return 0
    fi
    i=$((i + 1))
    sleep 1
  done
  echo "[vanblog] ERROR: $name did not become ready within ${max}s at $url"
  return 1
}

# --- Cleanup on exit ---
cleanup() {
  echo "[vanblog] shutting down..."
  kill "$MONITOR_PID" 2>/dev/null || true
  kill $PB_PID $THEME_HOST_PID $CADDY_PID $PI_PROXY_PID 2>/dev/null || true
  wait $PB_PID $THEME_HOST_PID $CADDY_PID $PI_PROXY_PID 2>/dev/null || true
}
trap cleanup EXIT INT TERM

# === Caddy: bootstrap + admin API ===

# 1. Start Caddy with bootstrap.json (background, NOT exec)
echo "[vanblog] starting Caddy with bootstrap config ($BOOTSTRAP_JSON)..."
caddy run --config "$BOOTSTRAP_JSON" &
CADDY_PID=$!

# 2. Wait for Caddy admin API to be reachable
wait_for "http://127.0.0.1:2019/config/" "Caddy admin API" 30 || exit 1

# 3. Start PocketBase (--hooksWatch for hot reload of JSVM hooks)
echo "[vanblog] starting PocketBase..."
PB_PACKS_FLAG=""
if [ -n "$VANBLOG_PACKS_DIR" ]; then
  echo "[vanblog] local Pack overrides: $VANBLOG_PACKS_DIR"
  PB_PACKS_FLAG="--packsDir=$VANBLOG_PACKS_DIR"
fi
vanblog serve --http=$PB_HTTP --dir=$PB_DATA --hooksWatch --coreSchemaPath=/core/models.js ${PB_PACKS_FLAG:+"$PB_PACKS_FLAG"} &
PB_PID=$!
wait_for "http://127.0.0.1:8090/api/health" "PocketBase" 30 || exit 1

# 3.5. Write agent.env — credentials/navigation for AI agents (Pi/Claude/Cursor).
# Agents source /etc/vanblog/agent.env to call pb REST API via @vanblog/sdk.
# Admin password is NOT embedded here; agents obtain a token via:
#   POST /api/collections/users/auth-with-password {email,password}
# using VANBLOG_EMAIL (set in docker-compose) + the password the operator chose
# during first-run setup. See AGENTS.md (§环境) for the fallback flow.
mkdir -p /etc/vanblog
# Recognise the compose placeholder so we don't write a misleading email.
AGENT_EMAIL="${VANBLOG_EMAIL:-}"
[ "$AGENT_EMAIL" = "admin@example.com" ] && AGENT_EMAIL=""
cat > /etc/vanblog/agent.env <<EOF
# Vanblog agent environment — generated by entrypoint.dev.sh at container start.
# Source this file (\`. /etc/vanblog/agent.env\`) to get SDK-ready env vars.
export PB_URL=http://127.0.0.1:8090
export ASTRO_URL=http://127.0.0.1:4321
export VANBLOG_MODE=dev
export VANBLOG_EMAIL=$AGENT_EMAIL
# Admin password: NOT stored here. Run first-run setup if VANBLOG_EMAIL is empty
# (check via: curl -s http://127.0.0.1:8090/api/vanblog/setup/status).
EOF
chmod 600 /etc/vanblog/agent.env
echo "[vanblog] agent.env written to /etc/vanblog/agent.env (see AGENTS.md §环境)"

# 3.6. Initialize pi coding agent config — resolve live Zen free model + write trust.
# Fail-open: if init-pi-config fails (network down), pi still starts with
# the hardcoded fallback model from .pi/settings.json.
echo "[vanblog] initializing pi agent config..."
node /workspace/scripts/init-pi-config.mjs || echo "[vanblog] pi config init skipped (will use fallback)"

# 3.7. Start the Zen auth-stripping proxy used by pi's OpenCode Zen provider.
# The Go agent manager starts one native pi RPC process per persisted session.
echo "[vanblog] starting pi model proxy..."
node /workspace/scripts/pi-zen-proxy.mjs &
PI_PROXY_PID=$!

# 4. Start Theme Host (loads active theme's SSR handler, routes /admin to app)
DEFAULT_THEME=$(cat /etc/vanblog/default-theme 2>/dev/null || echo "vanblog")
echo "[vanblog] starting theme host (default theme: ${DEFAULT_THEME})"
VANBLOG_THEMES_DIR=/var/lib/vanblog/themes \
VANBLOG_THEMES_BUILTIN_DIR=/build/themes \
VANBLOG_DEFAULT_THEME=${DEFAULT_THEME} \
VANBLOG_ADMIN_DIST_DIR=/build/app/dist \
PB_URL=http://127.0.0.1:8090 \
  node /workspace/app/src/theme-host/index.mjs &
THEME_HOST_PID=$!
wait_for "http://127.0.0.1:4321/__theme_host_health" "Theme Host" 30 || exit 1

# 5. Background monitor: if any child crashes, kill the container
monitor_children() {
  while true; do
    if ! kill -0 $CADDY_PID 2>/dev/null; then echo "[vanblog] FATAL: Caddy died"; exit 1; fi
    if ! kill -0 $PB_PID 2>/dev/null; then echo "[vanblog] FATAL: PocketBase died"; exit 1; fi
    if ! kill -0 $THEME_HOST_PID 2>/dev/null; then echo "[vanblog] FATAL: Theme Host died"; exit 1; fi
    if ! kill -0 $PI_PROXY_PID 2>/dev/null; then echo "[vanblog] FATAL: pi model proxy died"; exit 1; fi
    sleep 5
  done
}
monitor_children &
MONITOR_PID=$!

# 6. Wait for Caddy process (Caddy is no longer PID 1, entrypoint is).
# pb's OnBootstrap hook will call LoadConfig to inject full routes (dev variant).
echo "[vanblog] all services up, caddy bootstrap will be replaced by pb OnBootstrap hook"
echo "[vanblog] container is in foreground wait mode"
wait $CADDY_PID
