import { client } from '../client';

export const settingService = {
  getSiteInfo: client.getSiteInfo,
  updateSiteInfo: client.updateSiteInfo,
  getLayoutSettings: client.getLayoutSettings,
  updateLayoutSettings: client.updateLayoutSettings,
  getThemeSettings: client.getThemeSettings,
  updateThemeSettings: client.updateThemeSettings,
  getFriendLinks: client.getFriendLinks,
  createFriendLink: client.createFriendLink,
  updateFriendLink: client.updateFriendLink,
  deleteFriendLink: client.deleteFriendLink,
  getNavigation: client.getNavigation,
  updateNavigation: client.updateNavigation,
  getCustomCode: client.getCustomCode,
  updateCustomCode: client.updateCustomCode,
  getAboutInfo: client.getAboutInfo,
  updateAboutInfo: client.updateAboutInfo,
  getSocials: client.getSocials,
  updateSocial: client.updateSocial,
  deleteSocial: client.deleteSocial,
  getSocialTypes: client.getSocialTypes,
  getWalineSetting: client.getWalineSetting,
  updateWalineSetting: client.updateWalineSetting,
  getISRSetting: client.getISRSetting,
  updateISRSetting: client.updateISRSetting,
  getLoginSetting: client.getLoginSetting,
  updateLoginSetting: client.updateLoginSetting,
  getHttpsSetting: client.getHttpsSetting,
  updateHttpsSetting: client.updateHttpsSetting,
  getStaticSetting: client.getStaticSetting,
  updateStaticSetting: client.updateStaticSetting,
  getRewards: client.getRewards,
  createReward: client.createReward,
  updateReward: client.updateReward,
  deleteReward: client.deleteReward,
  getCaddyLog: client.getCaddyLog,
  clearCaddyLog: client.clearCaddyLog,
  getCaddyConfig: client.getCaddyConfig,
};
